# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_scsi"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2a13e514-e140-430f-8106-0f52329b8646";
    fsType = "btrfs";
    options = [
      "subvol=@/root"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8DE2-E04E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2a13e514-e140-430f-8106-0f52329b8646";
    fsType = "btrfs";
    options = [ "subvol=@/home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/2a13e514-e140-430f-8106-0f52329b8646";
    fsType = "btrfs";
    options = [
      "subvol=@/nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/2a13e514-e140-430f-8106-0f52329b8646";
    fsType = "btrfs";
    options = [
      "subvol=@/persist"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/lib" = {
    device = "/dev/disk/by-uuid/2a13e514-e140-430f-8106-0f52329b8646";
    fsType = "btrfs";
    options = [
      "subvol=@/var-lib"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/2a13e514-e140-430f-8106-0f52329b8646";
    fsType = "btrfs";
    options = [
      "subvol=@/var-log"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/disk/by-uuid/2a13e514-e140-430f-8106-0f52329b8646";
    fsType = "btrfs";
    options = [
      "subvol=@/var-tmp"
      "compress=zstd"
      "noatime"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
